# Configuration for deployment to kubernetes
apiVersion: v1
kind: Namespace
metadata:
    name: server-namespace
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: server-namespace
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1

  deplyement
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: server
          image: %{REGISTRY_URL}server:server_image
          imagePullPolicy: Always
          env:
          - name: ENV
            value: "production"
          - name: SERVICE_NAME
            value: "app-backend"
          - name: VERSION
            value: "prod-1.0"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server-namespace
spec:
  selector:
    app: server
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  namespace: server-namespace
  annotations:
    networking.gke.io/managed-certificates: ""
spec:
  backend:
    serviceName: server-service
    servicePort: 80
