name: CI
on:
  push:
    branches:
      - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Setup gcloud CLI
    - name: GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Auth
      run: |
        gcloud auth configure-docker
        gcloud container clusters get-credentials $GKE_CLUSTER           --zone $GKE_ZONE --project $GKE_PROJECT

    - name: Mount Bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...

    - name: Deploy
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" run :deploy.apply --define REGISTRY_URL=${REGISTRY_URL} --define GKE_PROJECT=${GKE_PROJECT} --define GKE_ZONE=${GKE_ZONE} --define GKE_CLUSTER=${GKE_CLUSTER}
  